project_id = "nzdnlwditksqpcyvxfgc"

[functions.admin-create-user]
verify_jwt = true

[functions.cleanup-trash]
verify_jwt = true

[functions.submit-lead]
verify_jwt = false

[functions.analyze-3a]
verify_jwt = false
