ALTER TABLE public.profiles
  ADD COLUMN IF NOT EXISTS leaderboard_visible BOOLEAN NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS peak_score_visible BOOLEAN NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS challenges_allowed BOOLEAN NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS auto_monthly_report BOOLEAN NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS deletion_requested_at TIMESTAMP WITH TIME ZONE DEFAULT NULL;